[general]
import = ["~/.config/alacritty/themes/rose-pine/rose-pine-moon.toml"]

[selection]
save_to_clipboard = true

[env]
TERM = "alacritty-direct"

[terminal.shell]
program = "/bin/bash"
args = ["-c", "tmux-attach.sh"]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 11.25

# Offset
offset = { x = 0, y = 0 }

# Glyph offset
glyph_offset = { x = 0, y = 0 }

# Builtin box drawing
builtin_box_drawing = true

[cursor]
style = { shape = "Block", blinking = "Off" }
# Set a different cursor for vi_mode (used in Neovim)
vi_mode_style = { shape = "Beam" }

[terminal]
osc52 = "CopyPaste"  # Explicitly allow OSC 52 clipboard operations
